//presenting my coding
#include<stdio.h>
#include<conio.h>
void main()
{
	int a,b,c;
	clrscr();				//to clear screen and start new programm
	printf("please enter first value=");    //print the output at display
	scanf("%d",&a);                	       //to take input from user
	printf("please enter the second value= ");
	scanf("%d",&b);

	c=ab;                                  // expression of bitwise operator

	printf("here is result =  %d", c);
	getch();                               //hold in screen

}