//this is single line comment
/*this is multi line comment
we can use to explain code */
#include<stdio.h>
#include<conio.h>
void main()
{
	clrscr();                                     // this is command is use to clear and screen
	printf("jai hindh && my name is kalpit jain");//print is use to print string
	getch();                                      //this is use to get out put
}

