// this is sigle line comment
/* this is multi line comment
we can use to vedanshu bitwise OR */
#include<stdio.h>
#include<conio.h>

     void main()
{
    int a,b,c;             // data type variable
    clrscr();
    printf("enter a value\t ");    // print a string
    scanf("%d%d",&a,&b);
    c=a|b;                         // expression
    printf("%d",c);                //print a value
    getch();


}