// this is single line comment
/* this is multi line comment
we can use Bitwise AND gate code */
#include<stdio.h>
#include<conio.h>

    void main()
{
     int a,b,c;                      // data type declare
     clrscr();                       // to clear screen
     printf("enter a value\n");      // print a string
     scanf("%d%d",&a,&b);
     c=a&b;                          // expression
     printf("%d",c);                 // print a value
     getch();                        // hold screen output


}